### PR TITLE
Created CoefficientPlot output module for LogisticRegression

### PR DESCRIPTION
**Pull request by lizhmartin**

### CODE REVIEW

**Comment by goldingn** [comment]
the last commit added two .DS_Store and one .Rapp.history objects to the repo. Could you remove them before I merge?

**Comment by lizhmartin** [comment]
Yes.

**Comment by lizhmartin** [comment]
I can delete them, will that suffice? I thought they were there and just not being monitored. I added all, that's how they got there. My bad, sorry. On that note, though, I added all because all the Output manuals updated with a link to the new Output module and I didn't want to add the individually. Solution?

**Comment by goldingn** [comment]
Cool. Yeah do `git rm <some file>` and commit & that'll be fine. 

Solution is:

`git commit -am "message" `

Doing `-am` instead of `-m` adds everything that's already being tracked by git.

Could also use a wildcard, like:
`git add man/*.Rd`

**Comment by lizhmartin** [comment]
Ok, I think I removed them. That wasn't what was causing the module to error with Travis (in Travis?) was it?

**Comment by goldingn** [comment]
It was not.

cloning your repo and doing: `zoon:::test_module('R/CoefficientPlot.R')` gives me:
```
# Error: Test failed: 'Check OUTPUT output formats for CoefficientPlot.R'
# * 
#   Your module failed to run with default parameters
# ERROR: Stopping workflow due to error in occurrence module. 
# 
# 
# You can debug this error by running the following code chunk 
# ===========
#   w <- workflow(occurrence = UKAnophelesPlumbeus, covariate = UKAir,process = Background(n = 70), model = LogisticRegression,output = CoefficientPlot) 
# ===========
#   1: stop(w)
# Timing stopped at: 0.352 0.043 46.56
```

which shows the workflow it's failing on. The message "Stopping workflow due to error in occurrence module." means that when run in this workflow, your module throws an error.

If I now do:
```r
library(zoon)
source('R/CoefficientPlot.R') # use the module as a locally-defined function
w <- workflow(occurrence = UKAnophelesPlumbeus,
              covariate = UKAir,
              process = Background(n = 70),
              model = LogisticRegression,
              output = CoefficientPlot)
```
I get:
```
Class of model object (from model module) has length > 1, using first value
```
```
Caught errors:
Error in inherits(class_modelObj, "character"): object 'class_modelObj' not found
```

which shows a typo in your module - I think this was supposed to be `class_model_obj`

**Comment by Doi90** [comment]
Side note: is there a difference between running source("function script
file") and LoadModule("module name")?

**Comment by Doi90** [comment]
Never mind, can't use LoadModule() on something that isn't on zoon yet,
obviously.

**Comment by goldingn** [comment]
Also, here's some advice you didn't ask for:

I think the first part of your module could be simplified from:

```r
  model_obj <- .model$model$model
  class_model_obj <- class(model_obj)
  
  if (length(class_model_obj) > 1) {
    message("Class of model object (from model module) has length > 1, using first value")
    class_model_obj <- class_model_obj[1]
  }
  
  if (!inherits(class_modelObj, "character")) 
    stop("CoefficientPlot: model class is not a character")
  
  if ( class_model_obj == "glm" ){ ... }
```

to 

```r
  model_obj <- .model$model$model
  if ( inherits(model_obj, "glm"){...}
```

This will go to your error message 'only for LogisticRegression' even if model_obj doesn't have a class. E.g. for a workflow using `NullModel`, `class(model_obj)` will return NULL, and this will only error on "CoefficientPlot: model class is not a character", which will be more confusing to users than your logistic regression one.

Also, your module always returns the coefficients and quits before it gets a chance to reset `par`, because of your return statement. You could switch those two lines.
Alternatively, if you want to be tidier, you could remove the `par(dev.par)` at the end and instead put:
```r
on.exit(par(dev.par))
```
right after you define `dev.par`. That will reset par even if your module errors, which your current version won't.

**Comment by lizhmartin** [comment]
Yes, but then I can't expand it to include other parametric models. The top bit is slightly modified from Tom's code for ImportanceVariables, which he also uses in PerformanceMeasures.

**Comment by lizhmartin** [comment]
Thanks. Side note: test_module() will run tests before pull requesting? Seems very sensible and something I was going to ask about.

**Comment by Doi90** [comment]
It does. I was running this command yesterday to see why I was timing out
on Travis.

system.time(zoon:::test_module("InteractiveOccurrenceMap.R"))

But I can pass on my computer where the packages are already installed, and
fail via Travis which needs to install said packages

**Comment by goldingn** [comment]
Good point, how about something like this?:

```r
model_obj <- .model$model$model
classes <- c('glm', 'mgcv', 'something')
if (!inherits(model_obj, c('glm', 'mgcv', 'something'))) {
  stop ('CoefficientPlots only works with model objects of class',
        paste(classes, sep = ', '),
        ', but this model object had class(es): ',
        paste(class(model_obj), sep = ', ')
)

if (inherits(model_obj, 'glm')) {
  #do something
} else if (inherits(model_obj, 'mgcv')) {
  # do something else
}
```

**Comment by lizhmartin** [comment]
Sure. Tom had a switch, which was neat.

I ran an mgcv::gam module last night and couldn't find (average/single) parameter estimates.

**Comment by lizhmartin** [comment]
Your message is better, though. Will update.

**Pull request merged**
