### PR TITLE
Malaria atlas

### PR DESCRIPTION
**Pull request by timcdlucas**
Add four new modules
* malariaAtlas_PR  - prevalence points from malaria atlas project
* malariaAtlas_covariates - rasters from malaria atlas project
* RemoveNAs - remove NAs from extracted points
* LonLatAsCovariates - Create new covariates from Longitude and Latitude. Eventually willbe used for spatial geostatistics type models.

### CODE REVIEW

**Comment by goldingn** [comment]
🔥screen shot 2018-04-20 at 10 41 59 pm🔥

**Comment by goldingn** [comment]
This looks awesome!

**Comment by timcdlucas** [comment]
I'm pretty excited about it. Is that "burn the mosquitos" or "Mosquitos. This shit is on fire!"?

The PR module is slightly odd because most of the modules only work with PA. So I've given an option to return data as PA or PR and sample size. Which is a bit weird. Might revisit the design at some point.

**Comment by goldingn** [comment]
Started off as the former, ended up the latter 😁

Ah right, that's a good point. Yeah, I think we talked about proportions as a data type at one point, but binomials is more tricky.

**Comment by timcdlucas** [comment]
Huh. Running a workflow with LonLatToCovariates seems to be failing.

```
> w2 <- workflow(malariaAtlas_PR(country = 'Zimbabwe', ISO = NULL, species = 'Pf', PA = TRUE),
+                malariaAtlas_covariates(surface = c('Plasmodium falciparum PR2-10', 
+                                                    'A global map of travel time to cities to assess inequalities in accessibility in 2015',
+                                                    'Duffy Negativity Phenotype Frequency'),
+                                        extent = c(27,33,-23,-17), year = c(2011, NA, NA)),
+                Chain(LonLatToCovariates, RemoveNAs),
+                LogisticRegression,
+                PrintMap)           
Error in parse(text = rawText) : <text>:22:65: unexpected input
21: #' @section Date submitted:  2017-04-25
22: LonLatToCovariates <- function (.data, lat = TRUE, lon = TRUE) {

```

So I'll have to work out what's wrong here. I would have thought something like this would have been caught by tests though. Sourcing the file works fine...
`source('https://raw.githubusercontent.com/zoonproject/modules/master/R/LonLatToCovariates.R')`


This is the workflow that made that pretty map I put on twitter by the way.

**Comment by timcdlucas** [comment]
Above issue fixed by PR https://github.com/zoonproject/modules/pull/167

**Pull request merged**
