### PR TITLE
remove par setting reset to allow users to set layout

### PR DESCRIPTION
**Pull request by lizhmartin**
Also added additional comments

### CODE REVIEW

**Comment by goldingn** [comment]
\*cough\* `devtools::document()` \*cough\*

**Comment by lizhmartin** [comment]
Can I do it now? After the fact?

**Comment by goldingn** [comment]
yup, just push to origin master and it'll appear here

**Comment by goldingn** [comment]
you mean install all the R packages needed to document?
`devtools::install_github('zoonproject/modules')`
but you shouldn't need to do that again this time, unless you've upgraded R and reset your library

**Comment by lizhmartin** [comment]
Found it on previous pull request - thanks. "RNCEP not available." I haven't upgraded R or reset my library. Not sure why it didn't have the dependencies.

**Comment by lizhmartin** [comment]
Hadn't pushed the new manual, sorry. There now.

**Pull request merged**
