### PR TITLE
Background default

### PR DESCRIPTION
**Pull request by goldingn**
Implementing this: https://github.com/zoonproject/zoon/issues/210#issuecomment-152212872
* deleting BiasBackground
* adding extra functionality to Background
* updating docs, including increment to roxygen2 v5.0.0

### CODE REVIEW

**Comment by goldingn** [comment]
no Travis run?

**Comment by AugustT** [comment]
This travis error seems to be intermittent and it is the result of a 403 error trying to install zoon from Github. I thought it might be because we are trying to call it simultaneously and maybe we are breaking some github API rule... seems strange though

**Comment by goldingn** [comment]
Could just be a slowdown on both services and some times of day?

See this Travis blog post about the issue:
http://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/

We may be able to add `travis_retry` to the github installation bit, if that's where it fails?

Will manually restart now

**Comment by goldingn** [comment]
this builds on my fork, so merging now

**Comment by AugustT** [comment]
I dont think this is the same issue as this is a 403 error. More like this:

https://github.com/DefinitelyTyped/tsd/issues/163

**Comment by AugustT** [comment]
Might be because Travis servers share IPs and therefore rate limits are easily reached

**Comment by goldingn** [comment]
Yeah, I think you're right. It make be easiest just to do something like:
 ```
- if [ $VERSION == devel ]; then sleep 5; fi
```
to delay one of the builds 5 seconds

**Comment by AugustT** [comment]
I'll try this on my fork

**Pull request merged**
