### PR TITLE
Added GenerateCovariateReport module. Builds a data profiling report …

### PR DESCRIPTION
**Pull request by Doi90**
…for the covariate data and outputs as an html

### CODE REVIEW

**Comment by goldingn** [comment]
This is failing because:

```
Authors@R field gives more than one person with maintainer role:
  Nick Golding <nick.golding.research@gmail.com> [aut, cre]
  David Wilkinson <davidpw@student.unimelb.edu.au> [aut, cre]
```

the `cre` role is the maintainer one, so you can just delete that and it should pass the checks

**Comment by Doi90** [comment]
I think our wires are crossed somewhere. The incorrect tag is in the
DESCRIPTION file for *zoontutorials* not *modules* (which is the pull
request you've commented on).

I've fixed this (maintainer tag) error now so its going through the Travis
checks. But this *modules* pull request has also failed the Travis checks.
I'll look into it

**Comment by goldingn** [comment]
Right you are, I was juggling too many PRs at once!

**Comment by goldingn** [comment]
Good job David!

I've fixed the rnbn issue and re-started the travis build. If it comes back green I'll merge right away

**Comment by Doi90** [comment]
Are we sure that Travis is using the .yml file from my branch when running these tests and not the one on zoonproject/modules? I made the changes you suggested so that the R packages were being installed before timing the module tests but it sill failed despite passing on my computer locally.

**Comment by goldingn** [comment]
Yep, positive. The issue is that you need to add the packages your module relies on: `mapr` and `htmlwidgets`.

**Comment by Doi90** [comment]
Righto, I'll try again.

**Comment by Doi90** [comment]
Ah, I see what I did. I was too focused on the first module not passing
that I didn't consider the other module so only added some of the packages
to the yml file

**Comment by Doi90** [comment]
Still no dice. If I run `system.time(zoon:::test_module("R/GenerateCovariateReport.R"))` it takes 25.80s.

**Comment by goldingn** [comment]
Yeah, it's installing them once first, and then installing them again when executing the module. One of the dependencies of DataExplorer is igraph, which takes  long time to install.
I imagine this is happening because travis installs packages in one library, but the r session invoked by checks are looking in another.

I think the best way around this is to list the dependencies in [the Depends section of DESCRIPTION](https://github.com/Doi90/modules/blob/master/DESCRIPTION#L13-L43). It would also be worth removing the r_packages entry from .travis.yml too, otherwise we're just wasting time installing things twice.

**Comment by goldingn** [comment]
We made it!

**Comment by Doi90** [comment]
Huzzah!

**Pull request merged**
