### PR TITLE
Add new module for converting lon lat to covariates.

### PR DESCRIPTION
**Pull request by timcdlucas**

### CODE REVIEW

**Comment by goldingn** [comment]
rnbn issue now fixed.

Can you document the module and push again? It should work this time

**Comment by timcdlucas** [comment]
Yes will do.

**Comment by timcdlucas** [comment]
That said, I can't work out what documentation is missing. Will have to read the manual...

**Comment by Doi90** [comment]
I'm pretty sure you just need to run the following:

roxygen2::roxygenise()

**Comment by timcdlucas** [comment]
Oh right yes of course. Thanks!

**Comment by timcdlucas** [comment]
I'll open a new PR with stuff in the coming days.

**Pull request closed without merging**
