### PR TITLE
Fixing extent lat long orders between spocc and bioclim modules.

### PR DESCRIPTION
**Pull request by timcdlucas**
Bioclim docs were wrong and spocc expected extent in a different order to Bioclim.

### CODE REVIEW

**Comment by goldingn** [comment]
see comments - could you roll back the re-ordered extents?

**Comment by goldingn** [comment]
arrgh, I have a doubt about switching `SpOcc` back now - since we're passing an argument called extent, not one called geometry, the `reorderedExtent` approach may be best. 

@timcdlucas don't bother changing anything for now until we've decided

what do you two think?

**Comment by goldingn** [comment]
Whatever we change, we have to amend `zoonDemo.R`, `vignettes/basic-zoon-usage.Rmd`, the docs for `modules::SpOcc` and all of the tests to be consistent

**Comment by timcdlucas** [comment]
Yes I was half way through changing the vignettes when we started discussing this. Also couldn't remember how to rebuild vignettes.

I think the core modules that we know are going to be used in tutorials etc. should be consistent.  I  think passing extent as an object will be quite a common thing to do.

    ext <- c(-10, 10, 45, 65)
    work2 <- workflow(occurrence = SpOcc(species = 'Eresus kollari', extent = ext),
                      covariate  = Bioclim(extent = ext),
                      process    = BackgroundAndCrossvalid(k = 2),
                      model      = RandomForest,
                      output     = PrintMap)     

especially when you are maybe doing a list of multiple occurrence and covariate modules. That's just good "don't repeat yourself."

However, in the long run, I'm sure there'll be inconsistencies. Which is annoying but probably unavoidable.

And I've also now learned why you do pull requests from a separate branch...

**Comment by goldingn** [comment]
Yup, that's good reasoning.
Will accept this and then go through fixing the other bits again

**Comment by goldingn** [comment]
OK, the order is now fixed in by https://github.com/goldingn/zoon/commit/97c6d73006d0c57868097dd00d13bc2638c44dd3

**Pull request merged**
