### PR TITLE
add new response curve Output module for presence-only, presence-back…

### PR DESCRIPTION
**Pull request by lizhmartin**
…ground, presence-absense data

### CODE REVIEW

**Comment by goldingn** [comment]
I've fixed the NBN issue now: https://github.com/zoonproject/modules/pull/130

Unfortunately you'll still have to document the package to generate the .Rd file for your new module before I can merge the PR.

**Comment by goldingn** [comment]
you should be able to automate installation of the modules package dependencies by doing something like: `devtools::install_github('zoonproject/modules')`

**Comment by lizhmartin** [comment]
Do I need to merge your changes to the repo first?

**Comment by goldingn** [comment]
I think so, yeah

**Pull request merged**
