### PR TITLE
Covariates histogram module

### PR DESCRIPTION
**Pull request by smwindecker**

### CODE REVIEW

**Comment by smwindecker** [comment]
not sure why Travis is failing - I've only added a simple module that passed during the BuildModule check.

**Comment by goldingn** [comment]
It's GBIF being flaky again. I've restarted and will try to keep restarting until GBIF is back up.

Prod me if I forget though!

**Comment by smwindecker** [comment]
No rush! It's Friday after all =) Glad I didn't forget something obvious. Though perhaps GBIF being flaky should have been predictable.. 

Thanks

**Comment by smwindecker** [comment]
Prod!

**Comment by smwindecker** [comment]
woo hoo!

**Comment by goldingn** [comment]
Did you accept  this PR before you closed it?

**Comment by goldingn** [comment]
:+1:

**Pull request merged**
