### PR TITLE
Beefing up interactive maps

### PR DESCRIPTION
**Pull request by goldingn**
This:
```r
library(zoon)
work2 <- workflow(occurrence = CWBZimbabwe,
                  covariate = Bioclim(extent = c(28, 38, -25, -15),
                                      res = 2.5),
                  process = NoProcess,
                  model = LogisticRegression,
                  output = list(InteractiveMap,
                                InteractiveCovariateMap(which = 2)))
```

Now gives something like this:

image

and this:

image

which is

image

### CODE REVIEW

**Comment by timcdlucas** [comment]
A reminder of why modules are cool. I don't need to update zoon to check this out.

**Comment by goldingn** [comment]
:+1:

**Comment by goldingn** [comment]
Unfortunately the covariates have to be on separate maps as I couldn't make a dynamic legend (I was hoping to have radio buttons for all of the covariates, but the legend would have been bad)

**Comment by Pakillo** [comment]
:clap: :clap: 
Guys you're doing an amazing work! :-)

**Pull request merged**
